### ISSUE TITLE
Subscriptions aren't resolving with renameRootFields and renameTypes transforms being used in tandem

### ISSUE THREAD

**Issue by apoggi-carecloud** [yaacovCR/graphql-tools-fork#17] opened 2019-08-21 17:00 UTC
When I use both renameRootFields and renameTypes together subscription data resolves to null still.

**Comment by yaacovCR** [comment] 2019-08-21 22:54
Huh! Can you share some code, will try to duplicate your setup.

**Comment by yaacovCR** [comment] 2019-08-22 03:24
Looks like we are already testing in tandem, see https://github.com/yaacovCR/graphql-tools-fork/blob/master/src/test/testAlternateMergeSchemas.ts#L148, but truth is RenameTypes does not do much unless fragments are being used or typenames are being queried.

**Comment by apoggi-carecloud** [comment] 2019-08-22 14:21
Fragments are being used and types names are being queried unfortunately.

**Comment by apoggi-carecloud** [comment] 2019-08-22 14:51
I'm using a pretty standard stitching implementation:
`const getRemoteSchema = async ({ uri, subUri, options = {}, customContext }) => {
  const httpLink = new HttpLink({ uri, fetch, ...options });
  const contextedLink = customContext ? customContext() : defaultContext();
  let link = null;

  if (subUri) {
    const wsLink = (operation, forward) => {
      const context = operation.getContext();
      const { identity } = get(context, ['graphqlContext'], {})
      const connectionParams = omitBy(
        {
          Authorization: `Bearer ${identity.accessToken}`,
          roleid: identity.roleId,
          Context: identity.securityContext,
        },
        isUndefined
      );
      const client = new SubscriptionClient(
        subUri,
        {
          connectionParams,
          reconnect: true,
        },
        ws
      );
      return client.request(operation);
    };

    link = contextedLink.concat(
      split(
        ({ query }) => {
          const { kind, operation } = getMainDefinition(query);
          return kind === 'OperationDefinition' && operation === 'subscription';
        },
        wsLink,
        httpLink
      )
    );
  } else {
    link = contextedLink.concat(httpLink);
  }

  const schema = await introspectSchema(link);

  return makeRemoteExecutableSchema({
    schema,
    link,
  });
};
`
Also applying these transforms to the types and root fields:
`const renameRootFields = ({term, prefixNotSuffix}) =>
  new RenameRootFields((operation, name) => (prefixNotSuffix ? `${term}${name}` : `${name}${term}`));

const renameTypes = ({term, prefixNotSuffix}) =>
  new RenameTypes(name => (prefixNotSuffix ? `${term}${name}` : `${name}${term}`));
`
I don't have any problems when executing queries or mutations, just resolving subscriptions when stitched

**Comment by apoggi-carecloud** [comment] 2019-08-22 14:53
The stitched service is written in Go using the gqlgen graphql implementation, but I don't think that would make a difference @yaacovCR

**Comment by yaacovCR** [comment] 2019-08-22 17:27
Can you also share the code where you apply the transforms. I wonder if you are applying more than one of each and that is the problem? If you could slim down to most minimal reproduction, that would be great.

**Comment by yaacovCR** [comment] 2019-08-23 02:32
And of course, please include schema, query and response. Would love to fix, just need details.

**Comment by yaacovCR** [comment] 2019-08-26 06:31
Closing for now -- let me know if you can provide a full reproduction, would be very helpful.

**Comment by apoggi-carecloud** [comment] 2019-08-28 22:41
@yaacovCR sorry for not getting back to you earlier. Here is a link to the stitched subscription server: https://github.com/apoggi-carecloud/graphql-tools-fork-example . I believe the issue could be related to the mergeSchemas function in graphql tools since thats being used. Let me know if you find anything. Thanks!

**Comment by yaacovCR** [comment] 2019-08-29 03:06
Only thing I can think of is that the order of the transforms is different in tests, the tests renames types first, have no idea why that would make a difference. Hopefully will be able to reproduce from your repo over weekend.

**Comment by yaacovCR** [comment] 2019-09-01 01:28
The problem is this line (https://github.com/apoggi-carecloud/graphql-tools-fork-example/blob/master/apollo_server/app.js#L11): You have to require 'graphql-tools-fork' rather than 'graphql-tools'

You can use [module-alias](https://www.npmjs.com/package/module-alias) to alias the graphql-tools package name if you want.

**Closed as completed by yaacovCR** 2019-09-01 01:28 UTC
